# Matugen Hyprland Colors

$background = rgb(f9f9ff)

$error = rgb(ba1a1a)

$error_container = rgb(ffdad6)

$inverse_on_surface = rgb(f0f0f7)

$inverse_primary = rgb(aec6ff)

$inverse_surface = rgb(2f3036)

$on_background = rgb(1a1b21)

$on_error = rgb(ffffff)

$on_error_container = rgb(410002)

$on_primary = rgb(ffffff)

$on_primary_container = rgb(001435)

$on_primary_fixed = rgb(001a42)

$on_primary_fixed_variant = rgb(0e4490)

$on_secondary = rgb(ffffff)

$on_secondary_container = rgb(354361)

$on_secondary_fixed = rgb(0b1b37)

$on_secondary_fixed_variant = rgb(394765)

$on_surface = rgb(1a1b21)

$on_surface_variant = rgb(434751)

$on_tertiary = rgb(ffffff)

$on_tertiary_container = rgb(1d1400)

$on_tertiary_fixed = rgb(251a00)

$on_tertiary_fixed_variant = rgb(5a4400)

$outline = rgb(737782)

$outline_variant = rgb(c3c6d3)

$primary = rgb(305caa)

$primary_container = rgb(78a0f2)

$primary_fixed = rgb(d8e2ff)

$primary_fixed_dim = rgb(aec6ff)

$scrim = rgb(000000)

$secondary = rgb(505e7e)

$secondary_container = rgb(cbdaff)

$secondary_fixed = rgb(d8e2ff)

$secondary_fixed_dim = rgb(b8c6eb)

$shadow = rgb(000000)

$source_color = rgb(78a0f2)

$surface = rgb(f9f9ff)

$surface_bright = rgb(f9f9ff)

$surface_container = rgb(ededf4)

$surface_container_high = rgb(e8e7ef)

$surface_container_highest = rgb(e2e2e9)

$surface_container_low = rgb(f3f3fa)

$surface_container_lowest = rgb(ffffff)

$surface_dim = rgb(d9d9e0)

$surface_tint = rgb(305caa)

$surface_variant = rgb(dfe2ef)

$tertiary = rgb(775a00)

$tertiary_container = rgb(c69b1f)

$tertiary_fixed = rgb(ffdf97)

$tertiary_fixed_dim = rgb(efc045)

