# Preload the image into memory
preload = /home/ahmed/personal/dots/.wallpaper/b-660.jpg

# Set the wallpaper (the first comma means "apply to all monitors")
wallpaper = ,/home/ahmed/personal/dots/.wallpaper/b-660.jpg
